### PR TITLE
Composer updated to Lumen 9

### PR DESCRIPTION
**Pull request by hbernaciak**
Changes proposed in this pull request:

Composer updated to Lumen 9.x

### CODE REVIEW

**Comment by hugovk** [comment]
Thank you!

**Comment by jorjsmile** [comment]
Can you make a tag for that merge ?

**Comment by hugovk** [comment]
Done! 🚀 

https://github.com/digiaonline/lumen-newrelic/releases/tag/4.1.0

**Comment by jorjsmile** [comment]
ty. Do you plan add also tag to nordsoftware/lumen-chained-exception-handler ? Sorry for being annoying )

**Comment by hugovk** [comment]
Not annoying at all, thanks for the prompt!

Done! 🚀 

https://github.com/digiaonline/lumen-chained-exception-handler/releases/tag/3.1.0

**Pull request merged**
