### PR TITLE
Add new newRelic.override_ini setting

### LINKED ISSUE #26: Transactions not showing up in New Relic
### What did you do?
Upgrade to 3.1.0
### What did you expect to happen?
My transactions to show up in New Relic
### What actually happened?
My transactions did not show up.
### What versions of relevant language, framework and this module are you using?
nordsoftware/lumen-newrelic: "3.1.0"
laravel/lumen-framework: "8.1"
php: "7.3"

In NewRelicMiddleware.php on line 46 newRelic->setAppName is called:
```php
$this->newRelic->setAppName(
    config('newRelic.application_name'),
    config('newRelic.license')
);
```
Which calls this function:
```php
public function setAppName( $name, $license = "", $xmit = false )
{
     return $this->call( 'newrelic_set_appname', array( $name, $license, $xmit ) );
}
```

The docblock states: 
```
* The xmit flag is new in version 3.1 of the agent. Usually, when you change an application name, the agent simply
* discards the current transaction and does not send any of the accumulated metrics to the daemon. However, if you
* want to record the metric and transaction data up to the point at which you called this function, you can specify
* a value of true for this argument to make the agent send the transaction to the daemon. This has a very slight
* performance impact as it takes a few milliseconds for the agent to dump its data. By default this parameter is
* false.
```
So when the NewRelicMiddleware is loaded (on the way out) the transaction up to that point is dropped. So the transactionName is not showing up in new relic. 

When I change the $xmit parameter to 'true' the transaction does show up in New Relic. If I completely remove the '$this->newRelic->setAppName()'-function the transaction is also showing up. 
```php
$this->newRelic->setAppName(
   config('newRelic.application_name'),
   config('newRelic.license'),
   true
);
```

On my server New Relic is already set up before creating the lumen app. So when calling the setAppName() it drops the transaction up to that point. 

I've spend way too much time on this and hope by creating this issue it prevents other people from wasting time. I will stay on v3.0.0 which works for me

### PR DESCRIPTION
**Pull request by miff2000**
Add new newRelic.override_ini to gate overriding the app name and license in the newrelic.ini file.
Update docs to include detail on possible slight performance impact and new environment variable

Fixes #26 

Changes proposed in this pull request:

 * Add new `NEW_RELIC_OVERRIDE_INI` / `newRelic.override_ini` setting to gate overriding the appName and licence details from the `newrelic.ini` file

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]

**Comment by Jalle19** [comment]
Looks good, thanks a lot!

**Comment by miff2000** [comment]
No probs!

**Comment by hugovk** [comment]
Thanks!

**Comment by Jalle19** [comment]
https://packagist.org/packages/nordsoftware/lumen-newrelic#3.1.1

**Pull request merged**
